[0m17:39:17.321513 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6027CFB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E602586AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E602AD9B90>]}


============================== 17:39:17.321513 | 6786fcdb-4f31-47a0-a565-80093a1ce024 ==============================
[0m17:39:17.321513 [info ] [MainThread]: Running with dbt=1.7.8
[0m17:39:17.321513 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\JulianGourmelon-aret\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init dbt-tutorial', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:39:17.329039 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/JulianGourmelon-aret/.dbt')}
[0m17:39:17.329039 [info ] [MainThread]: Creating dbt configuration folder at
[0m17:39:31.785711 [debug] [MainThread]: Starter project path: C:\Users\JulianGourmelon-aret\OneDrive - areto consulting gmbh\Dokumente\dbt_test\dbt-env\Lib\site-packages\dbt\include\starter_project
[0m17:39:31.893443 [info ] [MainThread]:
Your new dbt project "dbt_tutorial" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:39:31.896437 [info ] [MainThread]: Setting up your profile.
[0m17:40:27.398704 [info ] [MainThread]: Profile dbt_tutorial written to C:\Users\JulianGourmelon-aret\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:40:27.417745 [debug] [MainThread]: Command `dbt init` succeeded at 17:40:27.417002 after 70.11 seconds
[0m17:40:27.419686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E60250C090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E67B6CAB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E6028B2D10>]}
[0m17:40:27.422768 [debug] [MainThread]: Flushing usage events
[0m14:16:20.531343 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015734C93990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001572DAF3810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015734C92BD0>]}


============================== 14:16:20.549433 | 9dc3cc21-37c4-4012-b51d-ed69418b04fe ==============================
[0m14:16:20.549433 [info ] [MainThread]: Running with dbt=1.7.8
[0m14:16:20.560971 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\JulianGourmelon-aret\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m14:16:20.563973 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\JulianGourmelon-aret\OneDrive - areto consulting gmbh\Dokumente\dbt_test\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m14:16:20.569525 [debug] [MainThread]: Command `dbt run` failed at 14:16:20.569525 after 0.30 seconds
[0m14:16:20.574520 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015734C93650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001572DA18FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000015734F076D0>]}
[0m14:16:20.577054 [debug] [MainThread]: Flushing usage events
[0m13:14:11.062276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D97EDCC390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D97ED9D510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D97E4AB110>]}


============================== 13:14:11.075229 | 78baab1e-1e05-4b6d-8b35-b8773d6ae159 ==============================
[0m13:14:11.075229 [info ] [MainThread]: Running with dbt=1.7.8
[0m13:14:11.076231 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\JulianGourmelon-aret\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt test', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:14:11.077240 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\JulianGourmelon-aret\OneDrive - areto consulting gmbh\Dokumente\dbt_test\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m13:14:11.079231 [debug] [MainThread]: Command `dbt test` failed at 13:14:11.079231 after 0.11 seconds
[0m13:14:11.080475 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D97EDCD310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D97EDCC390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D977F8DA90>]}
[0m13:14:11.081483 [debug] [MainThread]: Flushing usage events
[0m17:03:07.275124 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED413AA690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED412D2E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED41920710>]}


============================== 17:03:07.285139 | 85d63ab0-7522-4729-ba7e-dad2b245d3ce ==============================
[0m17:03:07.285139 [info ] [MainThread]: Running with dbt=1.7.8
[0m17:03:07.285139 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\JulianGourmelon-aret\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt deps', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:03:07.285139 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\JulianGourmelon-aret\OneDrive - areto consulting gmbh\Dokumente\dbt_test\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m17:03:07.291146 [debug] [MainThread]: Command `dbt deps` failed at 17:03:07.291146 after 0.06 seconds
[0m17:03:07.292461 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED3A46AD50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED4133D350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED4133CCD0>]}
[0m17:03:07.293682 [debug] [MainThread]: Flushing usage events
[0m09:22:42.276776 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022709158450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022708CCF790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022705469FD0>]}


============================== 09:22:42.276776 | e4ace0f2-4803-40b1-a21b-3d413607c9dc ==============================
[0m09:22:42.276776 [info ] [MainThread]: Running with dbt=1.7.8
[0m09:22:42.276776 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\JulianGourmelon-aret\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m09:22:42.288792 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\JulianGourmelon-aret\OneDrive - areto consulting gmbh\Dokumente\dbt_test\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m09:22:42.288792 [debug] [MainThread]: Command `dbt run` failed at 09:22:42.288792 after 0.07 seconds
[0m09:22:42.288792 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022708C3C090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022708C3C150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022701DE0150>]}
[0m09:22:42.288792 [debug] [MainThread]: Flushing usage events
[0m10:49:58.038665 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152DB7BD390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152DBBAA290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152DBAB6AD0>]}


============================== 10:49:58.045525 | 82cef5d9-8e94-474d-8f79-64eac1ba4e5e ==============================
[0m10:49:58.045525 [info ] [MainThread]: Running with dbt=1.7.8
[0m10:49:58.046825 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\JulianGourmelon-aret\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt test', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:49:58.047828 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\JulianGourmelon-aret\OneDrive - areto consulting gmbh\Dokumente\dbt_test\dbt-tutorial\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m10:49:58.050271 [debug] [MainThread]: Command `dbt test` failed at 10:49:58.050271 after 0.06 seconds
[0m10:49:58.051283 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152DBBAA2D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152D49DBAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152DB85E8D0>]}
[0m10:49:58.052301 [debug] [MainThread]: Flushing usage events
